### ISSUE TITLE
Create custom TypeIDEntity without change vendor class

### ISSUE THREAD

**Issue by Gunzhin** [avto-dev/identity-laravel#2]
If I want create custom `TypeIDEntity` I must extend vendor class `IDEntity` that redefine methods `getTypesMap` & `make`. It's bad way. Will be great use config or different application environment.

**Comment by tarampampam** [comment]
This feature was added: https://github.com/avto-dev/identity-laravel/commit/d9f3c2576c5030d5f00cf16531900ed673595717

Release: https://github.com/avto-dev/identity-laravel/releases/tag/v2.4.0
