### ISSUE TITLE
Need possibility to block autodetect in type entity

### ISSUE THREAD

**Issue by Gunzhin** [avto-dev/identity-laravel#3]
If we want to create custom `TypeIDEntity` we must extend `make` method in `IDEntity` too. With property via `can_autodetect` we change only `getTypesMap` method. Of course, will be great if we mustn't extend vendor `IDEntity` and for this I created [issue#2](https://github.com/avto-dev/identity-laravel/issues/2)

**Comment by tarampampam** [comment]
Closed https://github.com/avto-dev/identity-laravel/pull/1
